services:
  - type: web
    name: beer-check-api
    env: python
    buildCommand: pip install -r api_requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: ratings-data
      mountPath: /opt/render/project/src
      sizeGB: 1 